# Generated by Django 4.2.4 on 2023-09-02 07:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeRequirement',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'quantity',
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                        verbose_name='Quantity',
                    ),
                ),
                (
                    'ingredient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='inventory.ingredient',
                        verbose_name='Ingredient',
                    ),
                ),
                (
                    'menu_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='inventory.menuitem',
                        verbose_name='Menu Item',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Recipe Requirement',
                'verbose_name_plural': 'Recipe Requirements',
                'indexes': [
                    models.Index(
                        fields=['menu_item'],
                        name='inventory_r_menu_it_547df4_idx',
                    ),
                    models.Index(
                        fields=['ingredient'],
                        name='inventory_r_ingredi_1c3923_idx',
                    ),
                ],
                'unique_together': {('menu_item', 'ingredient')},
            },
        ),
    ]
