# Generated by Django 4.2.4 on 2023-09-02 07:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_reciperequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'purchase_date',
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name='Purchase Date',
                    ),
                ),
                (
                    'customer_name',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name='Customer Name',
                    ),
                ),
                (
                    'quantity',
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name='Quantity',
                    ),
                ),
                (
                    'total_price',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                        verbose_name='Total Price',
                    ),
                ),
                (
                    'menu_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='inventory.menuitem',
                        verbose_name='Menu Item',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'indexes': [
                    models.Index(
                        fields=['menu_item'],
                        name='inventory_p_menu_it_17fd1e_idx',
                    ),
                    models.Index(
                        fields=['purchase_date'],
                        name='inventory_p_purchas_30b10b_idx',
                    ),
                ],
            },
        ),
    ]
